<script setup>
import CandidateList from './CandidateList.vue'

defineProps({
  result: { type: Object, default: null },
  mapping: { type: Object, default: () => ({}) },
  compatClass: { type: String, default: '' },
  sourceLabel: { type: String, default: '' },
  sourceClass: { type: String, default: '' },
  selectedCandidate: { type: Object, default: null },
})
</script>

<template>
  <div class="card" v-if="result && result.identity_resolution">
    <div class="step-header">
      <span class="step-badge">Step 1</span>
      <h2>Name resolution</h2>
      <span class="source-badge source-llm">LLM</span>
    </div>

    <p class="narrative">
      The input term <strong>"{{ result.term }}"</strong> was looked up against
      {{ result.nct_ids.length }} NCT record(s)
      (<code>{{ result.nct_ids.join(", ") }}</code>).
      The LLM classified it as
      <strong>{{ result.identity_resolution ? result.identity_resolution.resolution_kind : "unknown" }}</strong>
      and resolved it to
      <strong v-if="result.resolved_search_terms && result.resolved_search_terms.length">{{ result.resolved_search_terms.join(" / ") }}</strong>
      <span v-else>no searchable terms</span>
      for NCIt lookup.
    </p>

    <div class="meta-grid" style="margin-bottom: 0.75rem">
      <span class="meta-key">Resolution kind</span>
      <span class="meta-val">
        <span class="role-badge">{{ result.identity_resolution ? result.identity_resolution.resolution_kind : "—" }}</span>
      </span>
      <span class="meta-key">Normalized key</span>
      <span class="meta-val" style="font-style: italic; color: #374151">{{ result.normalized_term || "—" }}</span>
      <span class="meta-key">NCIt search terms</span>
      <span class="meta-val">
        <span v-if="result.resolved_search_terms && result.resolved_search_terms.length">{{ result.resolved_search_terms.join(", ") }}</span>
        <span v-else style="color: #9ca3af">none</span>
      </span>
    </div>

    <!-- NCIt search order pill row -->
    <div class="pill-row" v-if="result.resolved_search_terms && result.resolved_search_terms.length">
      <span class="pill-row-label">NCIt search order:</span>
      <span v-for="(t, i) in result.resolved_search_terms" :key="i" class="role-badge" style="font-size: 0.72rem">{{ t }}</span>
    </div>

    <div v-if="result.identity_resolution && result.identity_resolution.matches && result.identity_resolution.matches.length">
      <p class="section-divider">What the LLM extracted from the trial record</p>
      <table class="identity-table">
        <thead>
          <tr>
            <th>Search term</th>
            <th>Matched trial name</th>
            <th>Role</th>
            <th>Relationship</th>
            <th>Evidence</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="m in result.identity_resolution.matches" :key="m.search_term + m.role">
            <td><strong>{{ m.search_term }}</strong></td>
            <td style="color: #6b7280; font-size: 0.8rem">{{ m.matched_trial_name }}</td>
            <td><span class="role-badge">{{ m.role }}</span></td>
            <td style="font-size: 0.8rem">{{ m.relationship }}</td>
            <td style="font-size: 0.78rem; color: #6b7280; font-style: italic">{{ m.evidence }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="card" v-if="result && result.definition">
    <div class="step-header">
      <span class="step-badge">Step 2</span>
      <h2>Definition</h2>
      <span class="source-badge" :class="sourceClass">{{ sourceLabel }}</span>
    </div>

    <p class="narrative">
      <template v-if="result.definition_source === 'ncit'">
        A definition was found directly in <strong>NCIt</strong> by searching for
        <em>"{{ result.ncit_search_term }}"</em>.
        The preferred NCIt name is <strong>{{ result.ncit_preferred_name }}</strong>
        (<code class="meta-code">{{ result.ncit_code }}</code>).
      </template>
      <template v-else-if="result.definition_source === 'ncit_class_exemplar'">
        The term was a <strong>therapeutic-class request</strong>. The pipeline found an
        exemplar entity in NCIt (<strong>{{ result.ncit_preferred_name }}</strong>,
        <code class="meta-code">{{ result.ncit_code }}</code>) and used its definition
        to anchor the class mapping.
      </template>
      <template v-else-if="result.definition_source === 'ncit_components_plus_llm'">
        This is a <strong>regimen or composite product</strong>. Individual components were
        looked up in NCIt and the LLM synthesised a combined definition from their entries.
      </template>
      <template v-else>
        No NCIt entry was found for this term. The definition was
        <strong>generated by the LLM</strong> from ClinicalTrials.gov evidence.
      </template>
    </p>

    <p class="definition-text">{{ result.definition || "—" }}</p>

    <div class="pill-row" v-if="result.regimen_components && result.regimen_components.length">
      <span class="pill-row-label">Regimen components:</span>
      <span v-for="(rc, i) in result.regimen_components" :key="i" class="role-badge" style="font-size: 0.72rem">{{ rc }}</span>
    </div>

    <div v-if="result.ncit_code || result.ncit_search_term || result.ncit_preferred_name">
      <p class="section-divider">NCIt provenance</p>
      <div class="meta-grid">
        <template v-if="result.ncit_search_term">
          <span class="meta-key">Query sent to NCIt</span>
          <span class="meta-val"><em>{{ result.ncit_search_term }}</em></span>
        </template>
        <template v-if="result.ncit_preferred_name">
          <span class="meta-key">NCIt preferred name</span>
          <span class="meta-val">{{ result.ncit_preferred_name }}</span>
        </template>
        <template v-if="result.ncit_code">
          <span class="meta-key">NCIt code</span>
          <span class="meta-val"><code class="meta-code">{{ result.ncit_code }}</code></span>
        </template>
      </div>
    </div>

    <div v-if="result.ncit_component_concepts && result.ncit_component_concepts.length">
      <p class="section-divider">Component definitions pulled from NCIt</p>
      <div v-for="c in result.ncit_component_concepts" :key="c.search_term" class="component-block">
        <div class="component-header">
          {{ c.search_term }}
          <code v-if="c.ncit_code" class="meta-code" style="font-weight: 400; margin-left: 0.4rem">{{ c.ncit_code }}</code>
        </div>
        <div class="component-def">{{ c.definition }}</div>
      </div>
    </div>

    <!-- LLM draft — always shown when present -->
    <div v-if="result.llm_definition">
      <p class="section-divider">LLM draft</p>
      <p class="llm-draft" style="font-style: italic">{{ result.llm_definition }}</p>
    </div>
  </div>

  <!-- STEP 3: Category suggestion + Qdrant candidates -->
  <div class="card" v-if="result && result.superclass_labels">
    <div class="step-header">
      <span class="step-badge">Step 3</span>
      <h2>Therapeutic category suggestion</h2>
      <span class="source-badge source-llm">LLM</span>
    </div>

    <p class="narrative">
      The LLM read the definition and proposed this three-level hierarchy.
      These labels were then used as SapBERT embedding queries into the Qdrant ontology index
      to retrieve the closest candidate terms.
    </p>

    <!-- Category ladder -->
    <div class="category-ladder">
      <div class="cat-level" v-if="result.superclass_labels.specific_category">
        <span class="cat-label">Specific</span>
        <span class="cat-value">{{ result.superclass_labels.specific_category }}</span>
      </div>
      <div class="cat-arrow" v-if="result.superclass_labels.broad_category">&#9650;</div>
      <div class="cat-level" v-if="result.superclass_labels.broad_category">
        <span class="cat-label">Broad</span>
        <span class="cat-value">{{ result.superclass_labels.broad_category }}</span>
      </div>
      <div class="cat-arrow" v-if="result.superclass_labels.root_category">&#9650;</div>
      <div class="cat-level" v-if="result.superclass_labels.root_category">
        <span class="cat-label">Root</span>
        <span class="cat-value">{{ result.superclass_labels.root_category }}</span>
      </div>
    </div>

    <template v-if="result.candidates && result.candidates.length">
      <p class="section-divider" style="margin-top: 1.25rem">
        Qdrant candidates retrieved ({{ result.candidates.length }})
      </p>
      <CandidateList :candidates="result.candidates" :selected-term="mapping.selected_term" />
    </template>
    <p v-else-if="!result.ontology_mapping" style="font-size: 0.8rem; color: #9ca3af; margin-top: 1rem">
      Retrieving candidates...
    </p>
  </div>

  <div class="card" v-if="result && result.ontology_mapping">
    <div class="step-header">
      <span class="step-badge">Step 4</span>
      <h2>Therapeutic Category Result</h2>
      <span class="source-badge source-llm">LLM</span>
    </div>
    <div class="mapping-result-box">
      <div class="mapping-result-label">Mapped therapeutic category</div>
      <div class="mapping-result-term">{{ mapping.selected_term || "NONE_OF_THE_ABOVE" }}</div>
      <div style="display: flex; gap: 0.5rem; align-items: center; flex-wrap: wrap; margin-top: 0.5rem">
        <span class="compat-badge" :class="compatClass">{{ mapping.compatibility || "none" }}</span>
        <span style="font-size: 0.8rem; color: #6b7280">match type: <strong>{{ mapping.match_type || "—" }}</strong></span>
      </div>
      <p class="mapping-reason" style="margin-top: 0.75rem">{{ mapping.reason || "—" }}</p>
    </div>

    <p class="section-divider" style="margin-top: 1.25rem">Mapping detail</p>
    <div class="meta-grid">
      <span class="meta-key">Selected term</span>
      <span class="meta-val">{{ mapping.selected_term || "NONE_OF_THE_ABOVE" }}</span>
      <span class="meta-key">Compatibility</span>
      <span class="meta-val"><span class="compat-badge" :class="compatClass">{{ mapping.compatibility || "—" }}</span></span>
      <span class="meta-key">Match type</span>
      <span class="meta-val"><strong>{{ mapping.match_type || "—" }}</strong></span>
      <span class="meta-key">Reason</span>
      <span class="meta-val" style="font-style: italic">{{ mapping.reason || "—" }}</span>
    </div>

    <div class="node-detail" v-if="selectedCandidate && mapping.selected_term !== 'NONE_OF_THE_ABOVE'">
      <div class="node-detail-title">Ontology node detail</div>
      <div class="node-doc" v-if="selectedCandidate.documentation">{{ selectedCandidate.documentation }}</div>
      <div class="node-id">
        <span v-if="selectedCandidate.durable_id">ID: <code>{{ selectedCandidate.durable_id }}</code></span>
        <span v-if="selectedCandidate.object_name" style="margin-left: 0.75rem">Object name: <code>{{ selectedCandidate.object_name }}</code></span>
      </div>
      <div class="node-relations" v-if="(selectedCandidate.parents && selectedCandidate.parents.length) || (selectedCandidate.children && selectedCandidate.children.length)">
        <div class="node-rel-group" v-if="selectedCandidate.parents && selectedCandidate.parents.length">
          <div class="node-rel-label">Parents</div>
          <div v-for="(p, pi) in selectedCandidate.parents" :key="pi" class="node-rel-item">{{ p.name }}</div>
        </div>
        <div class="node-rel-group" v-if="selectedCandidate.children && selectedCandidate.children.length">
          <div class="node-rel-label">Children</div>
          <div v-for="(ch, ci) in selectedCandidate.children" :key="ci" class="node-rel-item">{{ ch.name }}</div>
        </div>
      </div>
    </div>
  </div>
</template>
